# Generated by Django 3.2.8 on 2021-12-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_FSS', '0003_auto_20211216_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fssbook',
            name='Participant',
            field=models.ManyToManyField(blank=True, null=True, to='project_FSS.Participant'),
        ),
    ]
